### ISSUE TITLE
Doc : useless bridge interface parts

### ISSUE THREAD

**Issue by pgrange** [n0vember/cloudMe#1]
In the documentation (README), the section ''Bridge interface'' starts with several commands intended to bring a bridge interface up :

```
ip link add name bridge0 type bridge
ip link set bridge0 up
ip addr add 192.168.1.1/24 dev bridge0
```

This seems useless since a previous section named ''Network pre-requisites'' already deals with this part by suggesting to run ''cmnet''. 

Regards,

**Comment by pgrange** [comment]
This issue also applies to the ''dnsmasq'' section.

**Comment by n0vember** [comment]
Thank you for these remarks. They led to commit https://github.com/n0vember/cloudMe/commit/1d752dcfc4d50a2ce9d18062d8270c1f02d35d96 which makes the documentation clearer.

I also have merged an other part of this network documentation in cmnet (https://github.com/n0vember/cloudMe/commit/6139b3e342cf5efa5b660ab71b0771063cb76832)

I think cmnet will be better to become a service.
