### ISSUE TITLE
Doc : what is a vm group ? 

### ISSUE THREAD

**Issue by pgrange** [n0vember/cloudMe#2]
In section ''Using description file'' of the documentation (README), the expression ''vm group'' appears. 

This is the first time this expression is used in the documentation and I can't find its meening from context. 

I think one should explain this concept of ''vm group''. 

Regards,

**Comment by n0vember** [comment]
I hope https://github.com/n0vember/cloudMe/commit/0d27ae63b9c4110d195d1b921603eb9d29bfe258 will make things clearer :)
